#!/bin/bash

INPUT_FILE='./tadaa/tailwind/input.css'
OUTPUT_FILE='./tadaa/static/styles/tailwind.css'

__compilecss() {
  tailwindcss -i $INPUT_FILE -o $OUTPUT_FILE
}

__watchcss() {
  tailwindcss -i $INPUT_FILE -o $OUTPUT_FILE --watch
}

install() {
  pip install -r requirements.txt
}

build() {
  __compilecss
}

clean() {
  rm -rf ./instance
}

run() {
  python3 wsgi.py
}

start() {
  __watchcss &
  run
}
